// Questionnaires
const questionnaires_instructions = {
    type: jsPsychSurvey,
    survey_json: {
        showQuestionNumbers: false,
        completeText: "Continue",
        pages: [
            {
                elements: [
                    {
                        type: "html",
                        name: "questionnaires_intro_text",
                        html: `
                <div class="narrow-text" style="max-width: 800px; margin: 0 auto; text-align: center;">
                <h3>Questionnaires</h3>
                <p>We will continue with a series of questionnaires.</p>
                <p>It is important that you answer truthfully. Please read the statements carefully and answer according to what describes you the best.</p>
              </div>
              <audio autoplay>
                <source src="utils/ding.mp3" type="audio/mpeg">
              </audio>
            `,
                    },
                ],
            },
        ],
    },
    data: { screen: "Questionnaire_instructions" },
}

// Convernience function to shuffle an object (used internally)
function shuffleObject(obj) {
    const entries = Object.entries(obj)
    for (let i = entries.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[entries[i], entries[j]] = [entries[j], entries[i]]
    }
    return Object.fromEntries(entries)
}

// BAIT  ===============================================================================
// Copied from fictionART
// Beliefs about Artificial Images Technology (BAIT) v2.2
// History:
// - 1.0: BAIT-Original: Items specifically about CGI and artificial media originally in Makowski 2025 (FakeFace)
// - 2.0: BAIT-14: Validated in FictionEro (with new items + removal of "I think"), where it was mixed with the 6 most
//   loading items of the positive and negative attitutes dimensions from the General Attitudes towards
//   Artificial Intelligence Scale (GAAIS; Schepman et al., 2020, 2022)
// - BAIT-14: Used in FakeNewsValidation
// - 2.1: BAIT-12: Used in FakeFace2.
//   - Removed 2 GAAIS items (GAAIS_Negative_9, GAAIS_Positive_7)
//   - Replaced "Artificial Intelligence" with "AI
//   - Change display (Analog scale -> Likert scale)
// - 2.1: BAIT-12: Used in FictionEro 2
// - 2.2: BAIT-14: Used in FictionArt and FictionFilm
//   - Added 2 new items about art

const bait_items = {
    // BAIT-12 items used in FakeFace2 study
    BAIT_1_ImagesRealistic:
        "Current AI algorithms can generate very realistic images",
    BAIT_2_ImagesIssues:
        "Images of faces or people generated by AI always contain errors and artifacts",
    BAIT_3_VideosIssues:
        "Videos generated by AI have obvious problems that make them easy to spot as fake",
    BAIT_4_VideosRealistic:
        "Current AI algorithms can generate very realistic videos",
    BAIT_5_ImitatingReality:
        "Computer-Generated Images (CGI) are capable of perfectly imitating reality",
    BAIT_6_EnvironmentReal:
        "Technology allows the creation of environments that seem just as real as reality",
    BAIT_7_TextRealistic:
        "AI assistants can write texts that are indistinguishable from those written by humans",
    BAIT_8_TextIssues:
        "Documents and paragraphs written by AI usually read differently compared to Human productions",

    // Attitudes (adapted from GAAIS; Schepman et al., 2023)
    BAIT_9_Dangerous: "AI is dangerous",
    BAIT_10_Worry: "I am worried about future uses of AI",
    BAIT_11_Exciting: "AI is exciting",
    BAIT_12_Benefit: "Much of society will benefit from a future full of AI",

    // Additional art related items
    BAIT_13_ArtIssues:
        "Human-made art evokes stronger emotional responses than AI-generated art",
    BAIT_14_ArtRealistic:
        "AI-generated art can sometimes surpass human creativity and artistic value",

    BAIT_AttentionCheck:
        "I can show that I am Human and not an AI by answering all the way to the right",
}

function make_bait(items, required = true, ticks = ["Disagree", "Agree"]) {
    items = shuffleObject(items)

    // AI Expertise
    var ai_questions = [
        {
            title: "How knowledgeable do you consider yourself about Artificial Intelligence (AI) technology?",
            name: "BAIT_AI_Knowledge",
            type: "rating",
            displayMode: "buttons",
            isRequired: required,
            minRateDescription: "Not at all",
            maxRateDescription: "Expert",
            rateValues: [0, 1, 2, 3, 4, 5, 6],
        },
        {
            title: "How frequently do you use Artificial Intelligence (AI) tools or technologies in your daily life? ",
            description:
                "This includes tools like ChatGPT, image or art generators, and AI assistants.",
            name: "BAIT_AI_Use",
            type: "radiogroup",
            // displayMode: "buttons",
            isRequired: required,
            choices: [
                "Never",
                "A few times per month",
                "A few times per week",
                "Once a day",
                "A few times per day",
            ],
        },
    ]
    questions = []
    // Make questions
    for (const key of Object.keys(items)) {
        q = {
            title: items[key],
            name: key,
            type: "rating",
            displayMode: "buttons",
            // scaleColorMode: "colored",
            isRequired: required,
            minRateDescription: ticks[0],
            maxRateDescription: ticks[1],
            rateValues: [0, 1, 2, 3, 4, 5, 6],
        }
        questions.push(q)
    }

    return [
        { elements: ai_questions },
        {
            elements: questions,
            description:
                "We are interested in your thoughts about Artificial Intelligence (AI). Please read the statements below carefully and indicate the extent to which you agree with each statement.",
        },
    ]
}

const questionnaire_bait = {
    type: jsPsychSurvey,
    //on_finish: function () {
           // curr_progress = jsPsych.progressBar.progress;
          //  jsPsych.progressBar.progress = curr_progress + 0.075;
    //},
    survey_json: function () {
        return {
            title: "Artificial Intelligence",
            showQuestionNumbers: false,
            goNextPageAutomatic: true,
            pages: make_bait(bait_items),
        }
    },
    data: {
        screen: "questionnaire_bait",
    },
}

// BAIT FEEDBACK??

// MINT ===================================================================================================
// version matching the one in FictionArt
// Sum all items belonging to the same dimension to calculate score

const mint_items = {
    MINT_ExAc_1: "I can always accurately feel when I am about to fart",
    MINT_ExAc_2: "I can always accurately feel when I am about to sneeze",
    MINT_ExAc_3: "I can always accurately feel when I am about to burp",
    MINT_ReIA_4: "I always feel in my body if I am relaxed",
    MINT_ReIA_5: "I always know when I am relaxed",
    MINT_ReIA_6:
        "My body is always in the same specific state when I am relaxed",
    MINT_SexS_7:
        "During sex or masturbation, I often feel very strong sensations coming from my genital areas",
    MINT_SexS_8:
        "My genital organs are very sensitive to pleasant stimulations",
    MINT_SexS_9:
        "When I am sexually aroused, I often notice specific sensations in my genital area (e.g., tingling, warmth, wetness, stiffness, pulsations)",
    MINT_CaCo_10:
        "Sometimes my breathing becomes erratic or shallow and I often don't know why",
    MINT_CaCo_11:
        "I often feel like I can't get enough oxygen by breathing normally",
    MINT_CaCo_12: "Sometimes my heart starts racing and I often don't know why",
    MINT_Urin_13:
        "I sometimes feel like I need to urinate or defecate but when I go to the bathroom I produce less than I expected",
    MINT_Urin_14:
        "I often feel the need to urinate even when my bladder is not full",
    MINT_Urin_15:
        "Sometimes I am not sure whether I need to go to the toilet or not (to urinate or defecate)",
    MINT_Derm_16: "In general, my skin is very sensitive",
    MINT_Derm_17: "My skin is susceptible to itchy fabrics and materials",
    MINT_Derm_18:
        "I can notice even very subtle stimulations to my skin (e.g., very light touches)",
    MINT_Sati_19:
        "I don't always feel the need to eat until I am really hungry",
    MINT_Sati_20:
        "Sometimes I don't realise I was hungry until I ate something ",
    MINT_Sati_21:
        "I don't always feel the need to drink until I am really thirsty",
    MINT_Olfa_22: "I often check the smell of my armpits",
    MINT_Olfa_23: "I often check the smell of my own breath",
    MINT_Olfa_24: "I often check the smell of my farts",
    MINT_Resp_25: "In general, I am very sensitive to changes in my breathing",
    MINT_Resp_26: "I can notice even very subtle changes in my breathing",
    MINT_Resp_27:
        "I am always very aware of how I am breathing, even when I am calm",
    MINT_Card_28: "In general, I am very sensitive to changes in my heart rate",
    MINT_Card_29: "I often notice changes in my heart rate",
    MINT_Card_30:
        "I can notice even very subtle changes in the way my heart beats",
    MINT_Gast_31:
        "I can notice even very subtle changes in what my stomach is doing",
    MINT_Gast_32: "In general, I am very sensitive to what my stomach is doing",
    MINT_Gast_33:
        "I am always very aware of what my stomach is doing, even when I am calm",
    MINT_AttentionCheck:
        "I can always accurately answer to the extreme left on this question to show that I am reading it",
}

// This function formats each question into a jsPsych-survey question that contains information about the question format
function make_mint(items, required = true, ticks = ["Disagree", "Agree"]) {
    items = shuffleObject(items)

    questions = []

    // Make questions
    for (const key of Object.keys(items)) {
        q = {
            title: items[key],
            name: key,
            type: "rating",
            displayMode: "buttons",
            // scaleColorMode: "colored",
            isRequired: required,
            minRateDescription: ticks[0],
            maxRateDescription: ticks[1],
            rateValues: [0, 1, 2, 3, 4, 5, 6],
        }
        questions.push(q)
    }

    return { elements: questions }
}

// Questionnaire ================================================
const questionnaire_mint = {
    type: jsPsychSurvey,
    on_finish: function () {
            curr_progress = jsPsych.progressBar.progress;
            jsPsych.progressBar.progress = curr_progress + 0.1;
    },
    survey_json: function () {
        return {
            title: "About you and your body",
            description:
                "Please answer the following questions based on how accurately each statement describes you in general.",
            showQuestionNumbers: false,
            goNextPageAutomatic: true,
            pages: make_mint(mint_items),
        }
    },
    data: {
        screen: "questionnaire_mint",
    },
}

// MAIA-2 =================================================================================================
const items_maia = {
    MAIA_Noticing_1:
        "When I am tense I notice where the tension is located in my body",
    MAIA_Noticing_2: "I notice when I am uncomfortable in my body",
    MAIA_Noticing_3: "I notice where in my body I am comfortable",
    MAIA_Noticing_4:
        "I notice changes in my breathing, such as whether it slows down or speeds up",
    MAIA_NotDistracting_1_R:
        "I ignore physical tension or discomfort until they become more severe",
    MAIA_NotDistracting_2_R: "I distract myself from sensations of discomfort",
    MAIA_NotDistracting_3_R:
        "When I feel pain or discomfort, I try to power through it",
    MAIA_NotDistracting_4_R: "I try to ignore pain",
    MAIA_NotDistracting_5_R:
        "I push feelings of discomfort away by focusing on something",
    MAIA_NotDistracting_6_R:
        "When I feel unpleasant body sensations, I occupy myself with something else so I do not have to feel them",
    MAIA_NotWorrying_1_R: "When I feel physical pain, I become upset",
    MAIA_NotWorrying_2_R:
        "I start to worry that something is wrong if I feel any discomfort",
    MAIA_NotWorrying_3:
        "I can notice an unpleasant body sensation without worrying about it",
    MAIA_NotWorrying_4:
        "I can stay calm and not worry when I have feelings of discomfort or pain",
    MAIA_NotWorrying_5_R:
        "When I am in discomfort or pain I cannot get it out of my mind",
    MAIA_AttentionRegulation_1:
        "I can pay attention to my breath without being distracted by things happening around me",
    MAIA_AttentionRegulation_2:
        "I can maintain awareness of my inner bodily sensations even when there is a lot going on around me",
    MAIA_AttentionRegulation_3:
        "When I am in conversation with someone, I can pay attention to my posture",
    MAIA_AttentionRegulation_4:
        "I can return awareness to my body if I am distracted",
    MAIA_AttentionRegulation_5:
        "I can refocus my attention from thinking to sensing my body",
    MAIA_AttentionRegulation_6:
        "I can maintain awareness of my whole body even when a part of me is in pain or discomfort",
    MAIA_AttentionRegulation_7:
        "I am able to consciously focus on my body as a whole",
    MAIA_EmotionalAwareness_1: "I notice how my body changes when I am angry",
    MAIA_EmotionalAwareness_2:
        "When something is wrong in my life I can feel it in my body",
    MAIA_EmotionalAwareness_3:
        "I notice that my body feels different after a peaceful experience",
    MAIA_EmotionalAwareness_4:
        "I notice that my breathing becomes free and easy when I feel comfortable",
    MAIA_EmotionalAwareness_5:
        "I notice how my body changes when I feel happy / joyful",
    MAIA_SelfRegulation_1:
        "When I feel overwhelmed I can find a calm place inside",
    MAIA_SelfRegulation_2:
        "When I bring awareness to my body I feel a sense of calm",
    MAIA_SelfRegulation_3: "I can use my breath to reduce tension",
    MAIA_SelfRegulation_4:
        "When I am caught up in thoughts, I can calm my mind by focusing on my body/breathing",
    MAIA_BodyListening_1:
        "I listen for information from my body about my emotional state",
    MAIA_BodyListening_2:
        "When I am upset, I take time to explore how my body feels",
    MAIA_BodyListening_3: "I listen to my body to inform me about what to do",
    MAIA_Trusting_1: "I am at home in my body",
    MAIA_Trusting_2: "I feel my body is a safe place",
    MAIA_Trusting_3: "I trust my body sensations",
    MAIA_AttentionCheck_1:
        "I notice that for this item I am being asked to respond all the way to the right",
}

// This function formats each question into a jsPsych-survey question that contains information about the question format
function make_maia(items, required = true, ticks = ["Never", "Always"]) {
    items = shuffleObject(items)
    questions = []

    // Make questions
    for (const key of Object.keys(items)) {
        q = {
            title: items[key],
            name: key,
            type: "rating",
            displayMode: "buttons",
            // scaleColorMode: "colored",
            isRequired: required,
            minRateDescription: ticks[0],
            maxRateDescription: ticks[1],
            rateValues: [0, 1, 2, 3, 4, 5, 6],
        }
        questions.push(q)
    }

    return { elements: questions }
}

// Questionnaire ================================================
const questionnaire_maia = {
    type: jsPsychSurvey,
    on_finish: function () {
            curr_progress = jsPsych.progressBar.progress;
            jsPsych.progressBar.progress = curr_progress + 0.1;
    },
    survey_json: function () {
        return {
            title: "About you and your body",
            description:
                "Please indicate how often each statement applies to you generally in daily life.",
            showQuestionNumbers: false,
            goNextPageAutomatic: true,
            pages: make_maia(items_maia),
        }
    },
    data: {
        screen: "questionnaire_maia",
    },
}

// IAS =================================================================================================
const items_ias = {
    IAS_1: "I can always accurately perceive when my heart is beating fast",
    IAS_2: "I can always accurately perceive when I am hungry",
    IAS_3: "I can always accurately perceive when I am breathing fast",
    IAS_4: "I can always accurately perceive when I am thirsty",
    IAS_5: "I can always accurately perceive when I need to urinate",
    IAS_6: "I can always accurately perceive when I need to defecate",
    IAS_7: "I can always accurately perceive when I encounter different tastes",
    IAS_8: "I can always accurately perceive when I am going to vomit",
    IAS_9: "I can always accurately perceive when I am going to sneeze",
    IAS_10: "I can always accurately perceive when I am going to cough",
    IAS_11: "I can always accurately perceive when I am hot/cold",
    IAS_12: "I can always accurately perceive when I am sexually aroused",
    IAS_13: "I can always accurately perceive when I am going to pass wind",
    IAS_14: "I can always accurately perceive when I am going to burp",
    IAS_15: "I can always accurately perceive when my muscles are tired/sore",
    IAS_16: "I can always accurately perceive when I am going to get a bruise",
    IAS_17: "I can always accurately perceive when I am in pain",
    IAS_18: "I can always accurately perceive when my blood sugar is low",
    IAS_19: "I can always accurately perceive when someone is touching me affectionately rather than non-affectionately",
    IAS_20: "I can always accurately perceive when something is going to be ticklish",
    IAS_21: "I can always accurately perceive when something is going to be itchy",
    IAS_AttentionCheck_1:
        "I can always accurately perceive that for this statement I must choose the lowest option",
}

// This function formats each question into a jsPsych-survey question that contains information about the question format
function make_ias(
    items,
    required = true,
    ticks = ["Disagree Strongly", "Strongly Agree"]
) {
    items = shuffleObject(items)

    questions = []

    // Make questions
    for (const key of Object.keys(items)) {
        q = {
            title: items[key],
            name: key,
            type: "rating",
            displayMode: "buttons",
            // scaleColorMode: "colored",
            isRequired: required,
            minRateDescription: ticks[0],
            maxRateDescription: ticks[1],
            rateValues: [1, 2, 3, 4, 5],
        }
        questions.push(q)
    }

    return { elements: questions }
}

// Questionnaire ================================================
const questionnaire_ias = {
    type: jsPsychSurvey,
    on_finish: function () {
            curr_progress = jsPsych.progressBar.progress;
            jsPsych.progressBar.progress = curr_progress + 0.1;
    },
    survey_json: function () {
        return {
            title: "Bodily sensations",
            description:
                "Please rate on the scale how accurately you believe you can perceive each specific signals without using external cues, e.g. measuring your pulse.",
            showQuestionNumbers: false,
            goNextPageAutomatic: true,
            pages: make_ias(items_ias),
        }
    },
    data: {
        screen: "questionnaire_ias",
    },
}
